<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ScrollBinding</RootNamespace>
    <AssemblyName>ScrollBinding</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../.modules/OpenTabletDriver-0.7.x/OpenTabletDriver/OpenTabletDriver.csproj" />
    <ProjectReference Include="../ScrollBinding.Lib/ScrollBinding.Lib.csproj" />
  </ItemGroup>

</Project>
