name: Build Plugin

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          5.0.x
          6.0.x

    - name: Build
      run: bash ./build.sh

    - name: Remove PDB files
      run: |
        find ./build -name "*.pdb" -type f -delete

    - uses: actions/upload-artifact@main
      with:
        name: "ScrollBinding-0.5.x"
        path: |
          ./build/0.5.x/*.dll
          !./build/0.5.x/*.pdb

    - uses: actions/upload-artifact@main
      with:
        name: "ScrollBinding-0.6.x"
        path: |
          ./build/0.6.x/*.dll
          !./build/0.6.x/*.pdb